version: '3.8'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: strava
      MONGO_INITDB_ROOT_USERNAME: "myuser"
      MONGO_INITDB_ROOT_PASSWORD: "strava"
    container_name: "mongodb"
    ports:
      - '27017-27019:27017-27019'
    expose:
      - '27017-27019'